apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicetree
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicetree
  template:
    metadata:
      labels:
        app: servicetree
    spec:
      containers:
      - name: servicetree
        image: kimbahir/servicetree:latest
---
apiVersion: v1
kind: Service
metadata:
  name: servicetree 
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 8000
    port: 80
  selector:
    app: servicetree
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: servicetree
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - servicetree.bahir.dk
    secretName: servicetree-bahir-dk-tls
  rules:
  - host: servicetree.bahir.dk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: servicetree
            port: 
              number: 80
